name: Generate and Encrypt Secret

on:
  push:
    branches:
      - develop

jobs:
  generate-encrypt-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: 'actions/checkout@v4'

    - name: Set up SOPS
      run: |
        wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux -O sops
        chmod +x sops
        sudo mv sops /usr/local/bin/sops

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Generate Secret Manifest
      run: |
        echo "
        apiVersion: v1
        kind: Secret
        metadata:
          name: kbot
          namespace: kbot-ns
        data:
          token: $(echo -n ${{ secrets.TELEGRAM_TOKEN }} | base64)
          openweather: $(echo -n ${{ secrets.OPENWEATHER_API_KEY }} | base64)
        " > secret.yaml

    - name: Encrypt Secret Manifest with SOPS
      run: |
        sops -e -gcp-kms projects/p72-flux/locations/global/keyRings/sops-flux-3/cryptoKeys/sops-key-flux --encrypted-regex '^(data)$' secret.yaml > secret-enc.yaml

    - name: Authenticate with GitHub
      run: |
        git config --global user.email "y.kosiy@seosmart.ua"
        git config --global user.name "Yurii Kosiy"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/YuriiKosiy/flux-gitops-82.git

    - name: Commit and Push Encrypted Secret
      run: |
        mv secret-enc.yaml clusters/p72-flux/kbot/secret-enc.yaml
        git add clusters/p72-flux/kbot/secret-enc.yaml
        git commit -m "Update encrypted secret with Telegram and OpenWeather keys"
        git push origin main
