apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana-chart
        namespace: flux-system
  interval: 10m0s
  values:
    service:
      type: LoadBalancer  # Додаємо LoadBalancer для зовнішнього доступу
      port: 3000
    rbac:
      pspEnabled: false
    adminUser: admin
    adminPassword: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.monitoring.svc.cluster.local
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki.monitoring.svc.cluster.local:3100
            access: proxy
            isDefault: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        k8s-cluster-rsrc-use:
          gnetId: 6417
          revision: 1
          datasource: Prometheus