# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "docker.io"
  repository: "yuriikosiy/kbot"
  tag: "v1.0.12-6b9cc05"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
